### ISSUE TITLE
Training hangs after 3 epochs

### ISSUE THREAD

**Issue by faizankshaikh** [ebenolson/kaggle-whale#1]
Even after an hour, the training does not progress. it just stays there. How much time does it require for training?

![screenshot](https://cloud.githubusercontent.com/assets/8406903/13526139/fd1316a2-e22b-11e5-84fc-5dad8e79111a.png)

**Comment by ebenolson** [comment]
It takes around 100 epochs to get near peak performance. I don't remember the epoch time, but it was usually trained overnight on a Titan or GTX980. It also needs a lot of CPU power for batch generation to keep up with the GPU.

**Comment by faizankshaikh** [comment]
A mistake on my end. Train classifier tweaked "expects input images cropped to face region, 384x384".

 It now takes 2 min per epoch on GTX TitanX.
